apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
spec:
  selector:
    matchLabels:
      app: pg
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: pg
    spec:
      initContainers:
        - name: postgres-init
          image: postgres:latest
          command:
          - bash
          - "-c"
          - |
            set -ex
            [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
            ordinal=${BASH_REMATCH[1]}
            if [[ $ordinal -eq 0 ]]; then
              printf "I am the primary"
            else
              printf "I am a read-only replica"
            fi
        - name: empty-data
          image: busybox
          command: ['sh', '-c', 'sleep 5 && echo "deleting dir" && rm -rf /var/lib/postgresql/data/*']
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
          - name: postgres
            containerPort: 5432
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "pg_isready --host $POD_IP"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "pg_isready --host $POD_IP"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
          - name: restore-postgresql-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: restore-postgresql-storage
    spec:
      selector:
        matchLabels:
           app: restore-postgresql-storage
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeName: restore-postgres
Azeez.Olanrewaju@DCITSYS01-L statef
